version: '3.7'

services:
    database:
        image: lodene/tp-devops-database:latest
        networks:
          - app-network #nom du network
        environment: #variable d'environnement qu'on peut utiliser dans les fichiers de serv/ pour ne pas qu'il apparaisse en clair dans les fichiers
            - POSTGRES_DB=mydatabase 
            - POSTGRES_PASSWORD=pwd
            - POSTGRES_USER=myuser
    backend:
        image: lodene/tp-devops-backend:latest #nom de l'iamge avec la version 
        networks: 
          - app-network #nom du network
        depends_on: 
          - database #refere a la section 'database' de ce fichier
        environment: #variable d'environnement
            - DATABASE_PASSWORD=pwd 
            - DB=mydatabase 
            - USER=myuser 
            - URL=database:5432 

    httpd:
        image: lodene/tp-devops-httpd:latest
        ports:
          - "80:80" #port du server http du local et du contenaire
        networks:
          - app-network #nom du network
        depends_on:
          - backend #refere a la section 'bakend' de ce fichier

networks:
    app-network: #nom du network
