---
# tasks file for roles/app
- name: Launch Database
  docker_container:
    name: backend
    image: lodene/tp-devops-backend:latest
    networks:
      - name: "{{ docker_network_name }}"
  vars: #variable d'environnement
    URL: database:5432 
