---
# tasks file for roles/app
- name: Launch Database
  docker_container:
    name: database
    image: lodene/tp-devops-backend:latest
    env:
      POSTGRES_DB: "{{ database_name }}"
      POSTGRES_PASSWORD: "{{ database_password }}"
      POSTGRES_USER: "{{ database_user }}"
    networks:
      - name: "{{ docker_network_name }}"
