name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.AUTH_DOCKER_HUB_USERNAME }} -p ${{ secrets.AUTH_DOCKER_HUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api-student
          tags: ${{secrets.AUTH_DOCKER_HUB_USERNAME}}/tp-devops-backend:latest
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./sql
          tags: ${{secrets.AUTH_DOCKER_HUB_USERNAME}}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./serv
          tags: ${{secrets.AUTH_DOCKER_HUB_USERNAME}}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/master' }}
