name: test backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Run the Maven verify phase
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=rspid_cpe-devops -Dsonar.organization=rspid -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file simple-api-student-main/pom.xml
  # define job to build and publish docker image
  build-and-push-docker-image:
    needs: test-backend
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./simple-api-student
          # Note: tags has to be all lower-cas
          tags:  ${{secrets.AUTH_DOCKER_HUB_USERNAME}}/backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./sql
          tags: ${{secrets.AUTH_DOCKER_HUB_USERNAME}}/database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./serv
          tags: ${{secrets.AUTH_DOCKER_HUB_USERNAME}}/httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.AUTH_DOCKER_HUB_USERNAME }} -p ${{ secrets.AUTH_DOCKER_HUB_TOKEN }}

  
