name: CI devops 2023
on:
  push: #on précise les branches 
    branches: 
      [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs: #le 'job qu'il fait faire, cad checkouyt, compiler avec java 17 et faire "mvn package" sur le pom.xml
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test with Maven
        working-directory: simple-api-student
        run: mvn package 
